let /* bubble_sort */
	var sorted : int := 0
	type intArray = array of int
	function bubble_sort (x : intArray, n : int) = (
		let
			var changed : int := 1
			var temp : int := 0
		in
			while changed do (
				changed := 0;
				for i := 0 to n-1 do (
					if x [i] > x [i+1] then (
						changed := 1;
						temp := x [i];
						x [i] := x [i+1];
						x [i+1] := temp
					)
				)
			)
		end
	)
in
end